# Generated by Django 3.2.23 on 2023-11-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_position_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentID', models.CharField(max_length=10, unique=True)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
