# Generated by Django 3.2.23 on 2023-11-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentID',
            field=models.CharField(max_length=10),
        ),
    ]
