# Generated by Django 3.2.23 on 2023-11-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='ID',
            new_name='id',
        ),
    ]
