# Generated by Django 3.2.23 on 2023-11-06 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_id_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='selectedPositionID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.position'),
        ),
    ]
