# Generated by Django 4.2.7 on 2023-11-22 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_submission_selectedpositionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.student')),
                ('submissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.submission')),
            ],
            bases=('website.student',),
        ),
    ]
