# Generated by Django 4.2.7 on 2023-11-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Hired', 'Hired'), ('MCC Team Member', 'MCC Team Member')], default='Interview', max_length=255),
        ),
    ]
