# Generated by Django 4.2.7 on 2023-11-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Hired', 'Hired'), ('MCC Team Member', 'MCC Team Member')], default='Candidate', max_length=255),
        ),
    ]
