# Generated by Django 4.2.7 on 2023-11-23 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_candidate_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('Scheduling', 'Scheduling'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduling', max_length=255),
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField()),
                ('isApproved', models.BooleanField(default=False)),
                ('interviewID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.interview')),
            ],
        ),
    ]
