# Generated by Django 4.2.7 on 2023-11-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_interview_status_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='dateTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
