# Generated by Django 4.2.7 on 2023-11-24 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_interview_datetime_alter_interview_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('Interview', 'Interview'), ('Offered', 'Offered'), ('Rejected', 'Rejected'), ('Hired', 'Hired')], default='Candidate', max_length=255),
        ),
    ]
