# Generated by Django 4.2.7 on 2023-11-25 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='dateTime',
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.TextField(default='Remote'),
        ),
    ]
