from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path("admin-hub/", views.admin_hub, name='admin-hub'),
    path("student-hub/", views.student_hub, name='student-hub'),
    path("new_applicant/", views.new_applicant, name='new_applicant'),
    path("thank-you/", views.thank_you, name='thank-you'),
    path("view-my-applications/", views.view_student_applications, name='view-my-applications'),
    path("student-hub/applications/", views.applications, name='applications'),
    path("positions/", views.positions, name='positions'),
    path("add_position/", views.add_position, name='add_position'),
    path("edit_position/", views.edit_position, name='edit_position'),
    path("update_position/", views.update_position, name='update_position'),
    path("delete_position/", views.delete_position, name='delete_position'),
    path("applicants/", views.applicants, name='applicants'),
    path("candidates/", views.candidates, name='candidates'),
    path("add_interview/", views.add_interview, name='add_interview'),
    path("interview_completed/", views.interview_completed, name='interview_completed'),
    path("add_availability/", views.add_availability, name='add_availability'),
    path("select_availability/", views.select_availability, name='select_availability'),
    path("request_more_availability/", views.request_more_availability, name='request_more_availability'),
    path("cancel-interview/", views.cancel_interview, name='cancel_interview'),
    path("add_candidate/", views.add_candidate, name='add_candidate'),
    path("add_offer/", views.add_offer, name='add_offer'),
    path("accept_offer/", views.accept_offer, name='accept_offer'),
    path("reject_offer/", views.reject_offer, name='reject_offer'),
    path("interviews/", views.interviews, name='interviews'),
    path("offers/", views.offers, name='offers'),
    path("logout/", views.logout_user, name='logout'),
]
